#!/bin/bash

set -e

function install_from_aur() {
    name=$1
    repo=$2
    pkg_path=$3
    
    if [ -z "$repo" ]; then
        repo=$name
    fi
    
    echo $name
    if [ -n "$pkg_path" ]; then
        cp -fr  "$pkg_path/${name}" ${name}
    else
        git clone https://aur.archlinux.org/${repo}.git ${name}
    fi
    cd ${name}

    if [ "${name}" == "python-graph-tool" ]; then
        echo "Patching number of cores for compilation !!!! - MJ"
        sed -i.bac 's/-j 1/-j 64/' PKGBUILD
    fi
    
    makepkg -sri --noconfirm

    cd ../
    rm -fr ${name}
}

install_from_aur $*
